vim.opt.shiftwidth = 4
vim.opt.nu = true
vim.opt.cursorline = true
vim.opt.cursorlineopt = "number" -- Highlight both line and number (default)
vim.o.foldcolumn = "1"
vim.o.foldlevel = 99
vim.o.foldlevelstart = 99
vim.o.foldenable = true
vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
vim.opt.hlsearch = false
vim.opt.clipboard = "unnamedplus"
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.virtualedit = "block"
vim.opt.softtabstop = 4
vim.opt.updatetime = 50
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.ruler = false
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undofile = true
vim.opt.undodir = os.getenv("HOME") .. "/.nvim/undodir"
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 25
vim.g.mapleader = " "
vim.opt.shell = os.getenv("SHELL")
vim.g.clipboard = {
	name = "wl-clipboard",
	copy = {
		["+"] = "wl-copy",
		["*"] = "wl-copy",
	},
	paste = {
		["+"] = "wl-paste --no-newline",
		["*"] = "wl-paste --no-newline",
	},
	cache_enable = 0,
}
